#!/bin/bash
benchmark="LUD"
rm ~/gpgpu-sim_distribution
dir=$(pwd)
ln -s $dir ~/gpgpu-sim_distribution
set -e
clear
make -j > out.txt
cd ../benchmarks/rodinia/$benchmark
./LUD.sh
mv ../../../output/rodinia/$benchmark.OUT ../../../output/rodinia/$benchmark.OUT.MOD
